name: Tests
permissions:
  contents: read

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v6
      - name: Set up
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install npm
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Setup build environment
        run: |
          echo "PLUGINS_BUILD_DIR = \"${PWD}/plugins/\"" > website/config.py
          uv sync --extra dev
          npm install
          npm run build
      - name: Generate plugins
        run: uv run python plugins-generate.py
      - name: PyTest
        run: uv run pytest
